### ISSUE TITLE
The functions `get_pof`, `read_pof` e `pof_labeller` aren't working

### ISSUE THREAD

**Issue by tbernardesfaria** [cran/POFIBGE#1]
I'm trying to use the package, but when I run any of the following functions `get_pof`, `read_pof` e `pof_labeller` the return message says `The pof_example function is under development and will be available soon in package POFIBGE.`
Do you have any idea of when it will be available?
Thanks!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors and possibly URLs in the `DESCRIPTION` file. Thanks!

**Comment by Gabriel-Assuncao** [comment]
@tbernardesfaria, we kindly ask you to close this issue, as this repository is a mirror generated by the CRAN for the POFIBGE package and forward your questions directly to the customer service channel: pacotesipd@ibge.gov.br.
