### ISSUE TITLE
Survey consumo alimentar 

### ISSUE THREAD

**Issue by jeffersoncrono** [cran/POFIBGE#2]
Olá Gabriel, estou tentando extrair os dados da pof de consumo alimentar (POF 7) pelo pacote Survey mas não sei quais variáveis indicar nos argumentos strata, weights e ids. Quais fatores de expansão devo inserir na Survey? Te agradeço se puder tentar me ajudar. Att. Jefferson

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by Gabriel-Assuncao** [comment]
Prezado Jefferson, boa tarde.

Pedimos por gentileza que feche esta issue, pois este repositório é um espelho gerado pelo CRAN para o pacote POFIBGE, e para este caso em específico, encaminhe sua requisição por gentileza para o canal de atendimento ibge@ibge.gov.br.
